Show coverage report for all tests combined

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -58,16 +58,11 @@ jobs:
       - name: Run tests
         run: |
           mkdir reports/ || echo "Directory exists"
-          PYDANTIC_VERSION=${{ matrix.pydantic-version }} make test-ci ARGS="--junitxml=reports/junit/python${{ matrix.python-version }}-pydantic${{ matrix.pydantic-version }}.xml"
-
-      - name: Show test results
-        uses: mikepenz/action-junit-report@v5
-        if: success() || failure() # always run even if the previous step fails
-        with:
-          report_paths: reports/junit/*.xml
+          make test-ci UV_ARGS="--group test-pydantic-${{ matrix.pydantic-version }}" PYTEST_ARGS="--junitxml=reports/junit/python${{ matrix.python-version }}-pydantic${{ matrix.pydantic-version }}.xml"
 
       - name: Upload coverage results
         uses: actions/upload-artifact@v6
+        if: always()
         with:
           name: coverage-python-${{ matrix.python-version }}-pydantic-${{ matrix.pydantic-version }}-os-${{ matrix.os }}
           path: reports/*
@@ -76,6 +71,7 @@ jobs:
 
   all_done:
     name: Tests done
+    if: always()
     runs-on: ubuntu-latest
     needs: [tests]
 
@@ -104,6 +100,12 @@ jobs:
           path: reports/
           pattern: coverage-*
           merge-multiple: true
+
+      - name: Show test results
+        uses: mikepenz/action-junit-report@v5
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: reports/junit/*.xml
 
       - name: Generate coverate reports
         run: |
